version: '3.4'

services:
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoocls-api-prod
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_PORT=8095
      - ConnectionStrings__ERPConexion=DSN=CLS;UID=ODOO;PWD=ODOO;
      - Authentication__Library=speed400cs
      - Authentication__ApiKey=n/KbzsjflJp/wJI+t17W6pqm2cYQMpQe9LZbjWwD5S3zEYkM0zUf3tFsLmScpZG1le6gVsqDA3Qy8VFBdO4aAQ
    restart: unless-stopped
    
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoocls-api-dev
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_PORT=8081
      - ConnectionStrings__ERPConexion=DSN=CLS;UID=ODOO;PWD=ODOO;
      - Authentication__Library=speed400xx
      - Authentication__ApiKey=n/KbzsjflJp/wJI+t17W6pqm2cYQMpQe9LZbjWwD5S3zEYkM0zUf3tFsLmScpZG1le6gVsqDA3Qy8VFBdO4aAQ
    restart: unless-stopped

networks:
  odoocls-network:
    driver: bridge
