version: '3.4'

services:
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoocls-api-prod
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_PORT=8095
      - ConnectionStrings__ERPConexion=DSN=CLS;UID=ODOO;PWD=ODOO;
      - Authentication__Library=SPEED400CS
      - Authentication__ApiKey=n/KbzsjflJp/wJI+t17W6pqm2cYQMpQe9LZbjWwD5S3zEYkM0zUf3tFsLmScpZG1le6gVsqDA3Qy8VFBdO4aAQ
    volumes:
      - /etc/odbc.ini:/etc/odbc.ini:ro
      - /etc/odbcinst.ini:/etc/odbcinst.ini:ro
      - /opt/ibm:/opt/ibm:ro
    restart: unless-stopped
    
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoocls-api-dev
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_PORT=8081
      - ConnectionStrings__ERPConexion=DSN=CLS;UID=ODOO;PWD=ODOO;
      - Authentication__Library=SPEED400XX
      - Authentication__ApiKey=n/KbzsjflJp/wJI+t17W6pqm2cYQMpQe9LZbjWwD5S3zEYkM0zUf3tFsLmScpZG1le6gVsqDA3Qy8VFBdO4aAQ
    volumes:
      - /etc/odbc.ini:/etc/odbc.ini:ro
      - /etc/odbcinst.ini:/etc/odbcinst.ini:ro
      - /opt/ibm:/opt/ibm:ro
    restart: unless-stopped
